### PR TITLE
Migration 9/12 and Fixes Orientation

### PR DESCRIPTION
**Pull request by sandmman**
## Description

I was doing some review on iOS development and ended up migrating this to 9/12 in addition to fixing the theme and layout issues resulting from landscape mode.

I didn't realize until now that Chia had been working on a migration; however, it appears as though it can't log in at the moment. 

## How Has This Been Tested?

For some reason, logging in has been having issues going through the simulator, but when the app is put on a phone everything works fine.

## Checklist:
 - [x] I have submitted a CLA form
 - [x]  If applicable, I have updated the documentation accordingly.
 - [ ]  If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by rfdickerson** [comment]
Yeah! We're having issues with the Facebook SDK and Swift 3 lately... The change log for the Facebook SDK claims that they support XCode 8 GM.

**Comment by rfdickerson** [comment]
Wait, does this build for you? There were a lot of errors that I couldn't easily resolve.

**Comment by sandmman** [comment]
Yeah everything builds and I've been using it on my phone

**Comment by rfdickerson** [comment]
Cool! We got it working 👍 

Btw, we fixed the issue with Facebook login, too!

Thanks for the PR, @sandmman

**Pull request merged**
